services:
  
  api:
    ports:
      - "8080:8080"
    image: songs:${VERSION}
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ${SONGS_PATH}:/app/songs
    environment:
      - LISTEN_PATH=/app/songs
      - FILE_PATH=${FILE_PATH}